### PR TITLE
Screenshot update

### PR DESCRIPTION
**Pull request by qfma**
Hi there,

I updated the screenshots to the latest version of the CGC could (except for the last one) and added an instructional video to the README. This will hopefully make it easier for the users to see how a query works.

Please let me know if any additional changes are necessary. 

Cheers,
Fabian

### CODE REVIEW

**Comment by mattions** [comment]
This is great!

Can you have a look at the comments made on #1 and include the relevant one on the README?

Mostly the introduction about MAF files (in a similar fashion of the maftools) and also a little explanation of the result (or more what the plots signify and what to expect in general)

**Comment by qfma** [comment]
I have added some commits to address some of the issues in mentioned in #1 . @ricarda9 Can you have a quick look? 

Also, should we add a section on how to run the maftools on the platform?

Will update the description of the results.
Cheers,
Fabian

**Comment by mattions** [comment]
You mean how to launch the app and set up a task?

**Comment by qfma** [comment]
Yes, that is what I mean. Because at the moment the maftools results basically drop out of nowhere. But I am also not entirely sure how detailed this is supposed to be?

**Comment by mattions** [comment]
I think one more screenshot of the task setting up with maftools, could be
good to have.
If you want add it, ping me and I'll merge it.

**Comment by qfma** [comment]
Hi there, 

Added the missing bits. If you are happy, this should merge right away.

Cheers,
Fabian

**Pull request merged**
